### ISSUE TITLE
using the package in browser

### ISSUE THREAD

**Issue by atefBB** [micnews/load-fb-sdk#4]
Hey ! I try to use this package but I got this message : 
`window is not defined`.
Any ideas?

**Comment by ellell** [comment]
@atefBB How are you running it? This package is only meant for use in the browser.

**Comment by atefBB** [comment]
I see the `require()` statement so I say this is for nodejs !
Am I wrong? ^^

**Comment by iefserge** [comment]
@atefBB require can be used in the browser too, when packaged with browserify or webpack.

**Comment by atefBB** [comment]
Thx for the information. So I should use browserify or webpack to use this package in browser !

**Comment by ellell** [comment]
@atefBB yes, that should do it!
